#!/usr/bin/env sh
#
# This is a thin usage wrapper over src/service.ts.
#

if [ "$#" -ne 2 ]; then
    printf "%s\\n" "Usage: ${0} <universe.json> <wallet.json>" >&2
    exit 1
fi

universePath="${1}"
shift

walletPath="${1}"
shift

if [ ! -f "${universePath}" ]; then
    printf "%s\\n" "Error: File ${universePath} does not exist." >&2
    exit 1
fi

if [ ! -f "${walletPath}" ]; then
    printf "%s\\n" "Error: File ${walletPath} does not exist." >&2
    exit 1
fi

BASEDIR=$( cd "${0%/*}" 2>/dev/null && pwd )

cmd=$(command -v nodejs || command -v node)

if [ -z "${cmd}" ]; then
    printf "%s\\n" "Error: nodejs or node not found." >&2
    exit 1
fi

${cmd} -r ts-node/register "${BASEDIR}/src/service.ts" "${universePath}" "${walletPath}"
